/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.9
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// Route table entry object
type RouteTableEntry struct {
	Type_           *RouteTableEntryType         `json:"type"`
	ProtocolType    *RouteTableEntryProtocolType `json:"protocolType,omitempty"`
	State           *RouteTableEntryState        `json:"state"`
	Age             string                       `json:"age,omitempty"`
	Prefix          string                       `json:"prefix,omitempty"`
	NextHop         string                       `json:"nextHop,omitempty"`
	Metric          int32                        `json:"metric,omitempty"`
	LocalPreference int32                        `json:"localPreference,omitempty"`
	AsPath          []int32                      `json:"asPath,omitempty"`
	Connection      *RouteTableEntryConnection   `json:"connection,omitempty"`
	ChangeLog       *Changelog                   `json:"changeLog"`
}
