/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.10
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

type BgpActionData struct {
	// Routing Protocol URI
	Href string `json:"href,omitempty"`
	// Routing protocol identifier
	Uuid  string      `json:"uuid,omitempty"`
	Type_ *BgpActions `json:"type,omitempty"`
	// BGP action description
	Description string           `json:"description,omitempty"`
	State       *BgpActionStates `json:"state,omitempty"`
	Changelog   *Changelog       `json:"changelog,omitempty"`
}
