/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.10
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// LinkProtocolRequestType : Type of Link Protocol
type LinkProtocolRequestType string

// List of LinkProtocolRequestType
const (
	UNTAGGED_LinkProtocolRequestType    LinkProtocolRequestType = "UNTAGGED"
	DOT1_Q_LinkProtocolRequestType      LinkProtocolRequestType = "DOT1Q"
	QINQ_LinkProtocolRequestType        LinkProtocolRequestType = "QINQ"
	EVPN_VXLAN_LinkProtocolRequestType  LinkProtocolRequestType = "EVPN_VXLAN"
	UNTAGGEDEPL_LinkProtocolRequestType LinkProtocolRequestType = "UNTAGGEDEPL"
)
