/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.7
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// FabricGatewaySortBy : Possible field names to use on sorting
type FabricGatewaySortBy string

// List of FabricGatewaySortBy
const (
	NAME_FabricGatewaySortBy                        FabricGatewaySortBy = "/name"
	UUID_FabricGatewaySortBy                        FabricGatewaySortBy = "/uuid"
	STATE_FabricGatewaySortBy                       FabricGatewaySortBy = "/state"
	LOCATIONMETRO_CODE_FabricGatewaySortBy          FabricGatewaySortBy = "/location/metroCode"
	LOCATIONMETRO_NAME_FabricGatewaySortBy          FabricGatewaySortBy = "/location/metroName"
	PACKAGECODE_FabricGatewaySortBy                 FabricGatewaySortBy = "/package/code"
	CHANGE_LOGCREATED_DATE_TIME_FabricGatewaySortBy FabricGatewaySortBy = "/changeLog/createdDateTime"
	CHANGE_LOGUPDATED_DATE_TIME_FabricGatewaySortBy FabricGatewaySortBy = "/changeLog/updatedDateTime"
)
