/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.3.52
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// ResourceType : Filter type
type ResourceType string

// List of ResourceType
const (
	CONNECTION_ResourceType      ResourceType = "CONNECTION"
	GATEWAY_ResourceType         ResourceType = "GATEWAY"
	SERVICE_PROFILE_ResourceType ResourceType = "SERVICE_PROFILE"
	PORT_ResourceType            ResourceType = "PORT"
	NETWORK_ResourceType         ResourceType = "NETWORK"
)
