/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.9
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

type Link struct {
	// Resource URI
	Href string `json:"href,omitempty"`
	// OperationId from Swagger hub spec
	Rel string `json:"rel,omitempty"`
	// Http method type
	Method string `json:"method,omitempty"`
	// Content type for the response
	ContentType string `json:"contentType,omitempty"`
	// Authentication required or not
	Authenticate bool `json:"authenticate,omitempty"`
}
