/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.9
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// NetworkSortBy : Possible field names to use on sorting
type NetworkSortBy string

// List of NetworkSortBy
const (
	NAME_NetworkSortBy                        NetworkSortBy = "/name"
	UUID_NetworkSortBy                        NetworkSortBy = "/uuid"
	SCOPE_NetworkSortBy                       NetworkSortBy = "/scope"
	OPERATIONEQUINIX_STATUS_NetworkSortBy     NetworkSortBy = "/operation/equinixStatus"
	LOCATIONREGION_NetworkSortBy              NetworkSortBy = "/location/region"
	CHANGE_LOGCREATED_DATE_TIME_NetworkSortBy NetworkSortBy = "/changeLog/createdDateTime"
	CHANGE_LOGUPDATED_DATE_TIME_NetworkSortBy NetworkSortBy = "/changeLog/updatedDateTime"
)
