/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.9
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// VirtualConnectionPriceConnectionType : Virtual Connection type
type VirtualConnectionPriceConnectionType string

// List of VirtualConnectionPriceConnectionType
const (
	EVPL_VC_VirtualConnectionPriceConnectionType       VirtualConnectionPriceConnectionType = "EVPL_VC"
	EPL_VC_VirtualConnectionPriceConnectionType        VirtualConnectionPriceConnectionType = "EPL_VC"
	EC_VC_VirtualConnectionPriceConnectionType         VirtualConnectionPriceConnectionType = "EC_VC"
	IP_VC_VirtualConnectionPriceConnectionType         VirtualConnectionPriceConnectionType = "IP_VC"
	VD_CHAIN_VC_VirtualConnectionPriceConnectionType   VirtualConnectionPriceConnectionType = "VD_CHAIN_VC"
	ACCESS_EPL_VC_VirtualConnectionPriceConnectionType VirtualConnectionPriceConnectionType = "ACCESS_EPL_VC"
	EVPLAN_VC_VirtualConnectionPriceConnectionType     VirtualConnectionPriceConnectionType = "EVPLAN_VC"
	EPLAN_VC_VirtualConnectionPriceConnectionType      VirtualConnectionPriceConnectionType = "EPLAN_VC"
	IPWAN_VC_VirtualConnectionPriceConnectionType      VirtualConnectionPriceConnectionType = "IPWAN_VC"
)
