/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.10
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// CloudRouterAccessPointState : Access point lifecycle state
type CloudRouterAccessPointState string

// List of CloudRouterAccessPointState
const (
	PROVISIONED_CloudRouterAccessPointState       CloudRouterAccessPointState = "PROVISIONED"
	PROVISIONING_CloudRouterAccessPointState      CloudRouterAccessPointState = "PROVISIONING"
	DEPROVISIONING_CloudRouterAccessPointState    CloudRouterAccessPointState = "DEPROVISIONING"
	DEPROVISIONED_CloudRouterAccessPointState     CloudRouterAccessPointState = "DEPROVISIONED"
	LOCKED_CloudRouterAccessPointState            CloudRouterAccessPointState = "LOCKED"
	NOT_PROVISIONED_CloudRouterAccessPointState   CloudRouterAccessPointState = "NOT_PROVISIONED"
	NOT_DEPROVISIONED_CloudRouterAccessPointState CloudRouterAccessPointState = "NOT_DEPROVISIONED"
)
