/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.7
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// GET Services Health
type HealthResponse struct {
	// The Canonical URL at which the resource resides.
	Href string `json:"href,omitempty"`
	// Indicator of a version
	Version string `json:"version,omitempty"`
	// release details.
	Release string `json:"release,omitempty"`
	// status of a service
	State       string       `json:"state,omitempty"`
	ApiServices *ApiServices `json:"apiServices,omitempty"`
}
