/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.9
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// CloudRouterSortBy : Possible field names to use on sorting
type CloudRouterSortBy string

// List of CloudRouterSortBy
const (
	NAME_CloudRouterSortBy                        CloudRouterSortBy = "/name"
	UUID_CloudRouterSortBy                        CloudRouterSortBy = "/uuid"
	STATE_CloudRouterSortBy                       CloudRouterSortBy = "/state"
	LOCATIONMETRO_CODE_CloudRouterSortBy          CloudRouterSortBy = "/location/metroCode"
	LOCATIONMETRO_NAME_CloudRouterSortBy          CloudRouterSortBy = "/location/metroName"
	PACKAGECODE_CloudRouterSortBy                 CloudRouterSortBy = "/package/code"
	CHANGE_LOGCREATED_DATE_TIME_CloudRouterSortBy CloudRouterSortBy = "/changeLog/createdDateTime"
	CHANGE_LOGUPDATED_DATE_TIME_CloudRouterSortBy CloudRouterSortBy = "/changeLog/updatedDateTime"
)
